# Do not modify this file!  It was generated by ‘secrets-set’ 
# and may be overwritten by future invocations. 
# Please add age files to /etc/nixos/secrets/age/*.age 
{

  alphanumeric-secret = ./alphanumeric-secret.age;
  basic-auth = ./basic-auth.age;
  cloudflare-env = ./cloudflare-env.age;
  password = ./password.age;
  self-env = ./self-env.age;
  tailscale-cloudflare = ./tailscale-cloudflare.age;
  token = ./token.age;

  # Host should have to opt into secrets
  enable = false;

}
