{flake, ...}: {
  alby = "iokeahhehimjnekafflcihljlcjccdbe";
  auto-tab-discard-suspend = "jhnleheckmknfcgijgkadoemagpecfol";
  built-with = "dapjbgnjinbpoindlpdmhochffioedbn";
  chromium-web-store = flake.inputs.suderpkgs.pins.chromium.chromium-web-store.url;
  contextsearch = "ddippghibegbgpjcaaijbacfhjjeafjh";
  dark-reader = "eimadpbcbfnmbkopoojfekhnkhdbieeh";
  fake-data = "gchcfdihakkhjgfmokemfeembfokkajj";
  floccus-bookmarks-sync = "fnaicdffflnofjppbagibeoednhnbjhg";
  global-speed = "jpbjcnkcffbooppibceonlgknpkniiff";
  i-still-dont-care-about-cookies = "edibdbjcniadpccecjdfdjjppcpchdlm";
  one-password = "aeblfdkhhhdcdjpifhhbdiojplfjncoa";
  return-youtube-dislike = "gebbhagfogifgggkldgodflihgfeippi";
  sponsorblock = "mnjggcdmjocbbbhaepdhchncahnbgone";
  stylus = "clngdbkpkpeebahjckkjfobafhncgmne";
  tampermonkey = "dhdgffkkebhmkfjojejmpbldmpobfkfo";
  ublock-origin = "cjpalhdlnbpafiamejdnhcphjbkeiagm";
  ublock-origin-lite = "ddkjiahejlhfcafbddmgiahcphecmpfh";
}
