# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e3591e1c-e091-4e16-b55f-088ab195fec4";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5EE4-758D";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/e3591e1c-e091-4e16-b55f-088ab195fec4";
      fsType = "btrfs";
    };

  # fileSystems."/mnt/ssd" =
  #   { device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx1";
  #     fsType = "btrfs";
  #   };

  # fileSystems."/mnt/raid" =
  #   { device = "/dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx2";
  #     fsType = "btrfs";
  #   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bf5e86ac-c711-48fe-a274-de6dda7e7671"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # The option definition `hardware.video.hidpi.enable' no longer has any effect; please remove it. high-resolution display
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
