#!/usr/bin/env zsh

# Increase brightness
if [ "$1" = "up" ]; then
  brightnessctl set +5%

# Decrease brightness
elif [ "$1" = "down" ]; then
  brightnessctl set 5%-
fi

# Get brightness
val=$(brightnessctl i | grep -o '[^( ]*%' | tr -d '%')

# Send to wob
echo $val > $SWAYSOCK.wob
