{
  config,
  lib,
  pkgs,
  perSystem,
  ...
}: let
  cfg = config.wayland.windowManager.hyprland;
  luaCfg = cfg.lua;

  inherit (lib) concatMapStringsSep listToAttrs mkEnableOption mkIf mkOption nameValuePair optionalString types;

  waybarWatcher = pkgs.self.mkScript {
    path = [pkgs.socat pkgs.procps];
    text =
      # bash
      ''
        handle() {
          case $1 in
          workspacev2\>\>*)
            pkill -RTMIN+8 waybar
            ;;
          esac
        }
        socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
      '';
  };

  renderLuaString = value: builtins.toJSON value;

  renderLuaList = values:
    if values == []
    then "{}"
    else "{\n${concatMapStringsSep "\n" (value: "  ${renderLuaString value},") values}\n}";

  renderLuaMonitors = monitors:
    if monitors == []
    then "{}"
    else
      "{\n"
      + concatMapStringsSep "\n" (
        monitor: "  { output = ${renderLuaString monitor.output}, mode = ${renderLuaString monitor.mode}, position = ${renderLuaString monitor.position}, scale = ${renderLuaString monitor.scale}${optionalString monitor.disabled ", disabled = true"} },"
      )
      monitors
      + "\n}";

  renderLuaAttrs = attrs: let
    names = builtins.attrNames attrs;
  in
    if names == []
    then "{}"
    else
      "{\n"
      + concatMapStringsSep "\n" (name: "  ${name} = ${renderLuaString attrs.${name}},") names
      + "\n}";

  # Render inline per-feature Lua snippets into standard modules that expose
  # `apply(host, features)`. This keeps feature ownership in the Nix module
  # while still letting Hyprland load each feature independently.
  featureModule = name: body: ''
    local util = require("lib.util")

    local M = {}

    function M.apply(_, _)
    ${body}
    end

    return M
  '';

  generatedFeatureFiles = listToAttrs (map (name:
    nameValuePair ".config/hypr/features/${name}.lua" {
      text = featureModule name luaCfg.features.${name};
    }) (builtins.attrNames luaCfg.features));

  # Deterministic feature load order keeps runtime behavior predictable when
  # several modules contribute binds or rules.
  generatedFeatureList = ''
    return ${renderLuaList (builtins.attrNames luaCfg.features)}
  '';

  # Runtime values shared by the Lua loader. Keep this as plain data so the
  # shared Lua files can stay boring and host-agnostic.
  generatedFeatures = ''
    return {
      exec_once = ${renderLuaList (
      [
        "${pkgs.dbus}/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target"
        "${waybarWatcher}"
      ]
      ++ lib.optional cfg.enablePlugins "hyprctl plugin load ${perSystem.hypr-dynamic-cursors.default}/lib/libhypr-dynamic-cursors.so"
    )},
      exec = ${renderLuaList [
      "pkill -RTMIN+8 waybar"
      "chromium --no-startup-window"
      "chromium-agent --no-startup-window"
    ]},
      plugins = {
        dynamic_cursors = {
          enabled = ${
      if cfg.enablePlugins
      then "true"
      else "false"
    },
          path = ${renderLuaString "${perSystem.hypr-dynamic-cursors.default}/lib/libhypr-dynamic-cursors.so"},
        },
      },
    }
  '';

  # Host-specific monitor/env/startup overrides selected from Home Manager.
  generatedHost = ''
    return {
      name = ${renderLuaString luaCfg.host},
      monitors = ${renderLuaMonitors luaCfg.monitors},
      env = ${renderLuaAttrs luaCfg.env},
      exec_once = ${renderLuaList luaCfg.execOnce},
    }
  '';

  # Convert stylix colors from nix to lua variables
  stylixColor = name: let
    c = config.lib.stylix.colors;
    hex = c.${name};
    r = c."${name}-rgb-r";
    g = c."${name}-rgb-g";
    b = c."${name}-rgb-b";
  in ''
    ${name} = {
      hex = "#${hex}",
      raw = "${hex}",
      rgb = "rgb(${r},${g},${b})",
      rgb_hex = "rgb(${hex})",
      rgba = function(alpha)
        return "rgba(${r},${g},${b}," .. tostring(alpha) .. ")"
      end,
      rgba_hex = function(alpha_hex)
        return "rgba(${hex}" .. alpha_hex .. ")"
      end,
    },
  '';

  generatedStylix = ''
    -- Generated by Home Manager from Stylix.
    -- Do not edit by hand.

    return {
    ${stylixColor "base00"}
    ${stylixColor "base01"}
    ${stylixColor "base02"}
    ${stylixColor "base03"}
    ${stylixColor "base04"}
    ${stylixColor "base05"}
    ${stylixColor "base06"}
    ${stylixColor "base07"}
    ${stylixColor "base08"}
    ${stylixColor "base09"}
    ${stylixColor "base0A"}
    ${stylixColor "base0B"}
    ${stylixColor "base0C"}
    ${stylixColor "base0D"}
    ${stylixColor "base0E"}
    ${stylixColor "base0F"}
    }
  '';
in {
  config = mkIf luaCfg.enable {
    # Hyprland chooses Lua mode at compositor startup if hyprland.lua exists,
    # so keep this loader as a real Home Manager file rather than a writable
    # local-store copy.
    home.file =
      {
        ".config/hypr/hyprland.lua".source = ./lua/hyprland.lua;
        ".config/hypr/lib/util.lua".source = ./lua/lib/util.lua;
        ".config/hypr/conf/session.lua".source = ./lua/conf/session.lua;
        ".config/hypr/conf/look.lua".source = ./lua/conf/look.lua;
        ".config/hypr/conf/input.lua".source = ./lua/conf/input.lua;
        ".config/hypr/conf/layouts.lua".source = ./lua/conf/layouts.lua;
        ".config/hypr/conf/group.lua".source = ./lua/conf/group.lua;
        ".config/hypr/binds/main.lua".source = ./lua/binds/main.lua;
        ".config/hypr/rules/windows.lua".source = ./lua/rules/windows.lua;
        ".config/hypr/generated/features.lua".text = generatedFeatures;
        ".config/hypr/generated/host.lua".text = generatedHost;
        ".config/hypr/generated/feature-list.lua".text = generatedFeatureList;
        ".config/hypr/generated/stylix.lua".text = generatedStylix;
      }
      // generatedFeatureFiles;

    # Local init stays writable on purpose: quick scratchpad for experiments
    # without regenerating Home Manager output.
    home.localStorePath = [
      ".config/hypr/local/init.lua"
    ];

    persist.storage.directories = [".config/hypr/local"];
    tmpfiles.files = [".config/hypr/local/init.lua"];
  };
}
