{
  config,
  lib,
  pkgs,
  perSystem,
  ...
}: let
  cfg = config.wayland.windowManager.hyprland;
  inherit (lib) listToAttrs mkIf nameValuePair;
  inherit (builtins) attrNames;
  toLua = lib.generators.toLua {};

  generatedFeatureFiles = let
    # Render inline per-feature Lua snippets into standard modules that expose
    # `apply(host, features)`. This keeps feature ownership in the Nix module
    # while still letting Hyprland load each feature independently.
    featureModule = body: ''
      local util = require("lib.util")
      local M = {}
      function M.apply(_, _)
      ${body}
      end
      return M
    '';
  in
    listToAttrs (map (name:
      nameValuePair ".config/hypr/features/${name}.lua" {
        text = featureModule cfg.lua.features.${name};
      }) (attrNames cfg.lua.features));

  # Deterministic feature load order keeps runtime behavior predictable when
  # several modules contribute binds or rules.
  generatedFeatureList = ''
    return ${toLua (attrNames cfg.lua.features)}
  '';

  # Runtime values shared by the Lua loader. Keep this as plain data so the
  # shared Lua files can stay boring and host-agnostic.
  generatedFeatures = "return ${toLua {
    exec_once = [
      "chromium --no-startup-window"
      "chromium-agent --no-startup-window"
    ];
  }}";

  generatedHost = "return ${toLua {
    name = cfg.lua.host;
    inherit (cfg.lua) rounding monitors env;
    exec_once = cfg.lua.execOnce;
  }}";

  # Convert stylix colors from nix to lua variables
  stylixColor = name: let
    c = config.lib.stylix.colors;
    hex = c.${name};
    r = c."${name}-rgb-r";
    g = c."${name}-rgb-g";
    b = c."${name}-rgb-b";
  in ''
    ${name} = {
      hex = "#${hex}",
      raw = "${hex}",
      rgb = "rgb(${r},${g},${b})",
      rgb_hex = "rgb(${hex})",
      rgba = function(alpha)
        return "rgba(${r},${g},${b}," .. tostring(alpha) .. ")"
      end,
      rgba_hex = function(alpha_hex)
        return "rgba(${hex}" .. alpha_hex .. ")"
      end,
    },
  '';

  generatedStylix = ''
    -- Generated by Home Manager from Stylix.
    -- Do not edit by hand.

    return {
    ${stylixColor "base00"}
    ${stylixColor "base01"}
    ${stylixColor "base02"}
    ${stylixColor "base03"}
    ${stylixColor "base04"}
    ${stylixColor "base05"}
    ${stylixColor "base06"}
    ${stylixColor "base07"}
    ${stylixColor "base08"}
    ${stylixColor "base09"}
    ${stylixColor "base0A"}
    ${stylixColor "base0B"}
    ${stylixColor "base0C"}
    ${stylixColor "base0D"}
    ${stylixColor "base0E"}
    ${stylixColor "base0F"}
    }
  '';
in {
  config = mkIf cfg.lua.enable {
    wayland.windowManager.hyprland = {
      configType = "lua";
      extraConfig = builtins.readFile ./lua/hyprland.lua;
      settings."plugin.load" = lib.mkIf cfg.enablePlugins "${perSystem.hypr-dynamic-cursors.default}/lib/libhypr-dynamic-cursors.so";
    };

    home.file =
      {
        ".config/hypr/lib/util.lua".source = ./lua/lib/util.lua;
        ".config/hypr/conf/session.lua".source = ./lua/conf/session.lua;
        ".config/hypr/conf/look.lua".source = ./lua/conf/look.lua;
        ".config/hypr/conf/input.lua".source = ./lua/conf/input.lua;
        ".config/hypr/conf/layouts.lua".source = ./lua/conf/layouts.lua;
        ".config/hypr/conf/group.lua".source = ./lua/conf/group.lua;
        ".config/hypr/binds/main.lua".source = ./lua/binds/main.lua;
        ".config/hypr/rules/windows.lua".source = ./lua/rules/windows.lua;
        ".config/hypr/lib/keyd.lua".source = ./lua/lib/keyd.lua;
        ".config/hypr/generated/features.lua".text = generatedFeatures;
        ".config/hypr/generated/host.lua".text = generatedHost;
        ".config/hypr/generated/feature-list.lua".text = generatedFeatureList;
        ".config/hypr/generated/stylix.lua".text = generatedStylix;
      }
      // generatedFeatureFiles;

    # Local init stays writable on purpose: quick scratchpad for experiments
    # without regenerating Home Manager output.
    home.localStorePath = [
      ".config/hypr/local/init.lua"
    ];

    persist.storage.directories = [".config/hypr/local"];
    tmpfiles.files = [".config/hypr/local/init.lua"];
  };
}
