# Do not modify this file!  It was generated by ‘nixos secrets’ 
# and may be overwritten by future invocations. 
# Please add age files to /etc/nixos/secrets/files/*.age 
{

  alphanumeric-secret = ./alphanumeric-secret.age;
  basic-auth = ./basic-auth.age;
  cloudflare-env = ./cloudflare-env.age;
  immich-env = ./immich-env.age;
  password = ./password.age;
  password-encrypted = ./password-encrypted.age;
  smtp-env = ./smtp-env.age;
  traefik-env = ./traefik-env.age;

}
