{
 "title": "Blocky Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "blocky_url", "label": "blocky API URL", "query": "https://blocky.hub" },
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Blocking State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_blocking_enabled" }
   ]
  },
  {
   "title": "Blocking status",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<style type=\"text/css\">\n  .blocky_btn {\n    border: none;\n    cursor: pointer; \n    padding: 12px;\n    font-size: 16px;\n    min-width: 100px\n  }\n\n  .blocky_greenbtn { \n    background-color: #4CAF50;\n    color: white;\n  }\n\n  .blocky_redbtn { \n    background-color: #AF504C;\n    color: white;\n  }\n\n  .blocky_alert {\n    font-size: 14px\n  }\n</style>\n<div class=\"blocky_alert blocky_alert-warning fade in\">\n  <a href=\"#\" class=\"close\" data-dismiss=\"blocky_alert\" aria-label=\"close\" style=\"text-decoration:none\">&times;</a>Done!\n</div>\n<div>\n   <button class=\"blocky_btn blocky_greenbtn\" onclick=\"blocky_status_enable()\">On</button>\n   <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable5m()\">Off 5m</button>\n   <button class=\"blocky_btn blocky_redbtn\" onclick=\"blocky_status_disable30m()\">Off 30m</button>\n<div>\n\n\n<script type=\"text/javascript\">\n  function blocky_status_disable() {\n    blocky_status_switch(false, 0)\n  }\n\n  function blocky_status_disable5m() {\n    blocky_status_switch(false, 5*60)\n  }\n\n  function blocky_status_disable30m() {\n    blocky_status_switch(false, 30*60)\n  }\n\n  function blocky_status_enable() {\n    blocky_status_switch(true, 0)\n  }\n\n  function blocky_status_switch(enable, duration) {\n    var url = '$blocky_url';\n    op = enable ? 'enable' : 'disable?duration='+duration+\"s\"\n    $.get(url + '/api/blocking/'+op, function(data) {\n      showAlert()\n    })\n    .fail(function() {\n      alert( \"error\" );\n    })\n  }\n\n  var showAlert = function() {\n    // first show the alert\n    $('.blocky_alert').show().fadeTo(500, 1);\n    \n    // Now set a timeout to hide it\n    window.setTimeout(function() {\n      $(\".blocky_alert\").fadeTo(500, 0).slideUp(500, function() {\n        $(this).hide();\n      });\n    }, 3000);\n  }\n\n  // start with the alert hidden\n  $('.blocky_alert').hide();\n</script>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "blocky_build_info " }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_sum[$__range])) / sum(increase(blocky_request_duration_ms_count[$__range]))"
    }
   ]
  },
  {
   "title": "Number of blacklist entries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blocky_blacklist_cache) / sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=\"blocky\"})/sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Queries blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total{response_type=\"BLOCKED\"}[$__range])) / sum(increase(blocky_query_total[$__range])) "
    }
   ]
  },
  {
   "title": "Query count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_query_total[$__range]))) "
    }
   ]
  },
  {
   "title": "Cache entries count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(blocky_cache_entry_count)/ sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Cache hit/miss ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_cache_hit_count[$__range])) / (sum(increase(blocky_cache_hit_count[$__range])) + sum(increase(blocky_cache_miss_count[$__range])))"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_error_total[$__range]))"
    }
   ]
  },
  {
   "title": "Prefetch count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_prefetch_count[$__range])))"
    }
   ]
  },
  {
   "title": "Prefetch query rate per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(blocky_prefetch_count[5m])) * 60"
    }
   ]
  },
  {
   "title": "Percentage of prefetched cached entries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_prefetch_hit_count[$__range])) / (sum(increase(blocky_cache_hit_count[$__range])))"
    }
   ]
  },
  {
   "title": "Last list refresh",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() -blocky_last_list_group_refresh)/ sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Prefetch domain count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blocky_prefetch_domain_name_cache_count)/ sum(up{job=\"blocky\"})"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(blocky_query_total[5m])) * 60",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Request rate per client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client) (rate(blocky_query_total[5m])) * 60",
     "legendFormat": " {{client}}"
    }
   ]
  },
  {
   "title": "Upstream request duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (type) (ceil(increase(blocky_query_total[$__range]))))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Queries per client",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total[$__range]))))",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Blacklist by group",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, blocky_blacklist_cache) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Response reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (reason) (ceil(increase(blocky_response_total[$__range]))))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Response type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (response_type) (ceil(increase(blocky_response_total[$__range]))))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (response_code) (ceil(increase(blocky_response_total[$__range]))))",
     "legendFormat": "{{response_code}}"
    }
   ]
  }
 ]
}