# https://doc.wallabag.org/en/admin/parameters.html#default-parametersyml-file
# https://github.com/a8m/envsubst
parameters:
    database_driver: pdo_pgsql
    database_driver_class: ~
    database_host: ~
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: ~
    database_path: ~
    database_table_prefix: ~
    database_socket: /run/postgresql
    database_charset: utf8
    domain_name: https://${HOST_NAME:=127.0.0.1}
    mailer_transport: smtp
    mailer_user: ${EMAIL_HOST_USER:=~}
    mailer_password: ${EMAIL_HOST_PASSWORD:=~}
    mailer_host: ${EMAIL_HOST:=~}
    mailer_port: ${EMAIL_PORT:=~}
    mailer_encryption: tls
    mailer_auth_mode: plain
    locale: en
    secret: ${SECRET_KEY:=secret}
    twofactor_auth: true
    twofactor_sender: noreply@${HOST_NAME:=wallabag}
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: noreply@${HOST_NAME:=wallabag}
    rss_limit: 50
    rabbitmq_host: ~
    rabbitmq_port: ~
    rabbitmq_user: ~
    rabbitmq_password: ~
    rabbitmq_prefetch_count: ~
    redis_scheme: unix
    redis_host: ~
    redis_port: ~
    redis_path: /run/redis-wallabag/redis.sock
    redis_password: ~
    sentry_dsn: ~
    server_name: "Wallabag"
